//! Application state and update logic.

use crossterm::event::{KeyCode, KeyEvent, KeyModifiers};
use std::collections::HashSet;
use std::sync::{mpsc, Arc, Mutex};
use std::time::Instant;

// ---------------------------------------------------------------------------
// Random container name generator (adjective-noun)
// ---------------------------------------------------------------------------

const ADJECTIVES: &[&str] = &[
    "admiring",
    "adoring",
    "agitated",
    "amazing",
    "bold",
    "brave",
    "busy",
    "charming",
    "clever",
    "confident",
    "cool",
    "curious",
    "daring",
    "determined",
    "eager",
    "earnest",
    "elegant",
    "epic",
    "fervent",
    "fierce",
    "focused",
    "friendly",
    "gentle",
    "graceful",
    "happy",
    "hopeful",
    "jolly",
    "keen",
    "lively",
    "lucid",
    "merry",
    "nifty",
    "nimble",
    "peaceful",
    "quiet",
    "relaxed",
    "sharp",
    "sleepy",
    "stoic",
    "tender",
    "trusting",
    "upbeat",
    "vigilant",
    "vivid",
    "witty",
    "wonderful",
    "zealous",
];

const NOUNS: &[&str] = &[
    "albatross",
    "baboon",
    "bear",
    "beaver",
    "capybara",
    "cheetah",
    "condor",
    "crane",
    "dingo",
    "dolphin",
    "dragon",
    "eagle",
    "falcon",
    "ferret",
    "firefly",
    "flamingo",
    "gazelle",
    "gecko",
    "gibbon",
    "giraffe",
    "gorilla",
    "hawk",
    "hedgehog",
    "heron",
    "ibis",
    "iguana",
    "jaguar",
    "jellyfish",
    "kestrel",
    "kingfisher",
    "lemur",
    "leopard",
    "lynx",
    "meerkat",
    "narwhal",
    "ocelot",
    "osprey",
    "otter",
    "panda",
    "panther",
    "parrot",
    "peacock",
    "pelican",
    "penguin",
    "phoenix",
    "puffin",
    "raven",
    "seahorse",
    "sparrow",
    "squirrel",
    "swift",
    "tiger",
    "tortoise",
    "toucan",
    "vulture",
    "wombat",
    "zebra",
];

fn random_name() -> String {
    let seed = std::time::SystemTime::now()
        .duration_since(std::time::SystemTime::UNIX_EPOCH)
        .map(|d| d.as_nanos())
        .unwrap_or(42);
    let adj = ADJECTIVES[(seed as usize) % ADJECTIVES.len()];
    let noun = NOUNS[((seed >> 16) as usize) % NOUNS.len()];
    format!("{}-{}", adj, noun)
}

use crate::config::TuiConfig;
use crate::runner::Container;

// ---------------------------------------------------------------------------
// ImageInfo — parsed from `pelagos image ls --json`
// ---------------------------------------------------------------------------

#[derive(Debug, Clone, serde::Deserialize)]
pub struct ImageInfo {
    pub reference: String,
    pub digest: String,
    #[serde(default)]
    pub layers: Vec<String>,
}

impl ImageInfo {
    /// First 12 hex chars of the digest, without the "sha256:" prefix.
    pub fn short_digest(&self) -> &str {
        let hex = self.digest.strip_prefix("sha256:").unwrap_or(&self.digest);
        &hex[..hex.len().min(12)]
    }
}

// ---------------------------------------------------------------------------
// Subscription message (deserialized from `pelagos subscribe` NDJSON output)
// ---------------------------------------------------------------------------

/// Wire-format events from `pelagos subscribe`.  Must match `GuestEvent` in
/// pelagos-guest exactly (same `#[serde(tag = "type", rename_all = "snake_case")]`).
#[derive(Debug, Clone, serde::Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum SubscriptionMsg {
    Snapshot {
        containers: Vec<Container>,
        vm_running: bool,
    },
    ContainerStarted {
        container: Box<Container>,
    },
    ContainerExited {
        name: String,
        #[allow(dead_code)]
        exit_code: Option<i32>,
    },
    /// Periodic liveness ping from the guest (~5s interval).
    Heartbeat {
        #[allow(dead_code)]
        ts: u64,
    },
    /// Synthetic event generated by the subscription thread on disconnect.
    #[serde(skip)]
    Disconnected,
}

// ---------------------------------------------------------------------------
// ConfirmAction
// ---------------------------------------------------------------------------

/// The action being confirmed in `Mode::Confirm`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ConfirmAction {
    Stop,
    Restart,
    Remove,
    /// Stop then remove: used when at least one target is currently running.
    StopAndRemove,
    /// Remove an OCI image; `confirm_targets[0]` is the image reference.
    ImageRm,
}

impl ConfirmAction {
    /// Human-readable verb used in the confirmation prompt.
    pub fn verb(&self) -> &'static str {
        match self {
            ConfirmAction::Stop => "stop",
            ConfirmAction::Restart => "restart",
            ConfirmAction::Remove => "remove",
            ConfirmAction::StopAndRemove => "stop and remove",
            ConfirmAction::ImageRm => "remove image",
        }
    }

    /// The `pelagos` subcommand name.  `StopAndRemove` and `ImageRm` are
    /// handled specially in `execute_action_bg`.
    pub fn pelagos_cmd(&self) -> &'static str {
        match self {
            ConfirmAction::Stop => "stop",
            ConfirmAction::Restart => "restart",
            ConfirmAction::Remove => "rm",
            ConfirmAction::StopAndRemove => "rm",
            ConfirmAction::ImageRm => "image rm",
        }
    }
}

// ---------------------------------------------------------------------------
// Mode
// ---------------------------------------------------------------------------

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Mode {
    Normal,
    /// Image management screen (toggled with `I` from Normal).
    Images,
    /// Pull dialog: modeline becomes a `pull> <input>` text field.
    ImagePull,
    /// Scrollable overlay showing full image JSON detail.
    ImageInspect,
    ProfilePicker,
    /// Command palette: modeline becomes a `run> <input>` text field.
    CommandPalette,
    /// Waiting for y/N confirmation before executing an action on containers.
    Confirm,
    /// Waiting for y/N/q confirmation before quitting.
    ConfirmQuit,
    /// Scrollable inspect overlay showing full container detail.
    Inspect,
}

// ---------------------------------------------------------------------------
// App
// ---------------------------------------------------------------------------

pub struct App {
    pub mode: Mode,
    pub containers: Vec<Container>,
    /// Index of the highlighted row in Normal mode.
    pub selected: usize,
    /// Names of rows with Space-toggled multi-select (order preserved via containers list).
    pub selected_names: HashSet<String>,
    pub show_all: bool,
    pub profile: String,
    pub profiles: Vec<String>,
    pub vm_running: bool,
    pub last_refresh: Instant,
    pub profile_picker_selected: usize,
    pub should_quit: bool,
    pub palette_input: String,
    /// Set by the palette on Enter; main.rs drains this to spawn the run.
    pub pending_run: Option<String>,
    pub tui_config: TuiConfig,
    /// Set by confirm on 'y'; main.rs drains this to execute the action.
    pub pending_action: Option<(ConfirmAction, Vec<String>)>,
    /// Old profile name set on profile switch; main.rs stops that VM then
    /// bumps the subscription generation to connect to the new profile.
    pub pending_profile_switch: Option<String>,
    pub status_message: Option<String>,
    pub status_tx: Option<mpsc::SyncSender<String>>,
    pub status_rx: Option<mpsc::Receiver<String>>,
    pub subscription_reconnecting: bool,
    pub sub_config: Option<Arc<Mutex<crate::SubConfig>>>,
    pub last_any_msg: Instant,
    // Confirm mode state — valid only when mode == Mode::Confirm.
    pub confirm_action: Option<ConfirmAction>,
    pub confirm_targets: Vec<String>,
    // Inspect overlay state.
    /// Container name to fetch detail for; drained by main.rs to spawn the query.
    pub pending_inspect: Option<String>,
    /// Channel on which the background ps thread delivers the enriched Container.
    pub inspect_result_tx: Option<mpsc::SyncSender<Container>>,
    pub inspect_result_rx: Option<mpsc::Receiver<Container>>,
    /// The container whose detail is currently displayed.
    pub inspect_container: Option<Container>,
    /// Scroll offset within the inspect overlay (lines).
    pub inspect_scroll: usize,

    // Images screen state.
    pub images: Vec<ImageInfo>,
    pub images_selected: usize,
    pub images_loading: bool,
    pub images_error: Option<String>,
    /// Set to true to trigger a background image list fetch.
    pub pending_image_ls: bool,
    pub image_ls_tx: Option<mpsc::SyncSender<Result<Vec<ImageInfo>, String>>>,
    pub image_ls_rx: Option<mpsc::Receiver<Result<Vec<ImageInfo>, String>>>,
    /// Pull dialog text input.
    pub image_pull_input: String,
    /// Set to trigger a background pull; drained by main.rs.
    pub pending_image_pull: Option<String>,
    /// Set after image-rm confirmation; drained by main.rs.
    pub pending_image_rm: Option<String>,
    // Image inspect overlay state.
    /// Image reference to inspect; drained by main.rs to spawn the query.
    pub pending_image_inspect: Option<String>,
    pub image_inspect_tx: Option<mpsc::SyncSender<Result<String, String>>>,
    pub image_inspect_rx: Option<mpsc::Receiver<Result<String, String>>>,
    /// Pretty-printed JSON lines for the image inspect overlay.
    pub image_inspect_lines: Vec<String>,
    pub image_inspect_loading: bool,
    pub image_inspect_scroll: usize,
}

impl App {
    pub fn new(profile: String, profiles: Vec<String>) -> Self {
        let picker_idx = profiles.iter().position(|p| p == &profile).unwrap_or(0);
        let (status_tx, status_rx) = mpsc::sync_channel(8);
        let (inspect_tx, inspect_rx) = mpsc::sync_channel(1);
        let (image_ls_tx, image_ls_rx) = mpsc::sync_channel(1);
        let (image_inspect_tx, image_inspect_rx) = mpsc::sync_channel(1);
        let tui_config = TuiConfig::load(&profile);
        Self {
            mode: Mode::Normal,
            containers: Vec::new(),
            selected: 0,
            selected_names: HashSet::new(),
            show_all: false,
            profile,
            profiles,
            vm_running: false,
            last_refresh: Instant::now(),
            profile_picker_selected: picker_idx,
            should_quit: false,
            palette_input: String::new(),
            pending_run: None,
            tui_config,
            pending_action: None,
            pending_profile_switch: None,
            status_message: None,
            status_tx: Some(status_tx),
            status_rx: Some(status_rx),
            subscription_reconnecting: false,
            sub_config: None,
            last_any_msg: Instant::now(),
            confirm_action: None,
            confirm_targets: Vec::new(),
            pending_inspect: None,
            inspect_result_tx: Some(inspect_tx),
            inspect_result_rx: Some(inspect_rx),
            inspect_container: None,
            inspect_scroll: 0,
            images: Vec::new(),
            images_selected: 0,
            images_loading: false,
            images_error: None,
            pending_image_ls: false,
            image_ls_tx: Some(image_ls_tx),
            image_ls_rx: Some(image_ls_rx),
            image_pull_input: String::new(),
            pending_image_pull: None,
            pending_image_rm: None,
            pending_image_inspect: None,
            image_inspect_tx: Some(image_inspect_tx),
            image_inspect_rx: Some(image_inspect_rx),
            image_inspect_lines: Vec::new(),
            image_inspect_loading: false,
            image_inspect_scroll: 0,
        }
    }

    // -----------------------------------------------------------------------
    // Subscription event application
    // -----------------------------------------------------------------------

    pub fn apply_subscription(&mut self, msg: SubscriptionMsg) {
        if let Some(rx) = &self.status_rx {
            while let Ok(msg) = rx.try_recv() {
                self.status_message = Some(msg);
            }
        }
        self.last_any_msg = Instant::now();

        match msg {
            SubscriptionMsg::Snapshot {
                containers,
                vm_running,
            } => {
                self.containers = if self.show_all {
                    containers
                } else {
                    containers
                        .into_iter()
                        .filter(|c| c.status == "running")
                        .collect()
                };
                // Drop selections for containers no longer present.
                let present: HashSet<String> =
                    self.containers.iter().map(|c| c.name.clone()).collect();
                self.selected_names.retain(|n| present.contains(n));
                clamp_selected(&mut self.selected, self.containers.len());
                self.vm_running = vm_running;
                self.last_refresh = Instant::now();
                self.subscription_reconnecting = false;
                self.status_message = None;
            }

            SubscriptionMsg::ContainerStarted { container } => {
                if self.show_all || container.status == "running" {
                    if let Some(pos) = self
                        .containers
                        .iter()
                        .position(|c| c.name == container.name)
                    {
                        self.containers[pos] = *container;
                    } else {
                        self.containers.push(*container);
                    }
                }
                self.last_refresh = Instant::now();
            }

            SubscriptionMsg::ContainerExited { name, .. } => {
                if !self.show_all {
                    self.containers.retain(|c| c.name != name);
                    self.selected_names.remove(&name);
                    clamp_selected(&mut self.selected, self.containers.len());
                } else if let Some(c) = self.containers.iter_mut().find(|c| c.name == name) {
                    c.status = "exited".to_string();
                }
                self.last_refresh = Instant::now();
            }

            SubscriptionMsg::Heartbeat { .. } => {
                self.last_refresh = Instant::now();
            }

            SubscriptionMsg::Disconnected => {
                self.vm_running = false;
                self.subscription_reconnecting = true;
            }
        }
    }

    pub fn subscription_stale(&self) -> bool {
        !self.subscription_reconnecting && self.last_any_msg.elapsed().as_secs() > 15
    }

    // -----------------------------------------------------------------------
    // Key handling
    // -----------------------------------------------------------------------

    pub fn on_key(&mut self, key: KeyEvent) {
        match self.mode {
            Mode::Normal => self.on_key_normal(key),
            Mode::Images => self.on_key_images(key),
            Mode::ImagePull => self.on_key_image_pull(key),
            Mode::ImageInspect => self.on_key_image_inspect(key),
            Mode::ProfilePicker => self.on_key_profile_picker(key),
            Mode::CommandPalette => self.on_key_palette(key),
            Mode::Confirm => self.on_key_confirm(key),
            Mode::ConfirmQuit => self.on_key_confirm_quit(key),
            Mode::Inspect => self.on_key_inspect(key),
        }
    }

    fn on_key_normal(&mut self, key: KeyEvent) {
        match key.code {
            KeyCode::Char('q') => self.mode = Mode::ConfirmQuit,
            KeyCode::Char('c') if key.modifiers.contains(KeyModifiers::CONTROL) => {
                self.should_quit = true;
            }

            KeyCode::Char('j') | KeyCode::Down => {
                if !self.containers.is_empty() {
                    self.selected = (self.selected + 1).min(self.containers.len() - 1);
                }
            }
            KeyCode::Char('k') | KeyCode::Up => {
                self.selected = self.selected.saturating_sub(1);
            }

            // Space: toggle multi-select on highlighted row, then advance cursor.
            KeyCode::Char(' ') => {
                if let Some(c) = self.containers.get(self.selected) {
                    let name = c.name.clone();
                    if !self.selected_names.remove(&name) {
                        self.selected_names.insert(name);
                    }
                    if self.selected + 1 < self.containers.len() {
                        self.selected += 1;
                    }
                }
            }

            KeyCode::Char('a') => {
                self.show_all = !self.show_all;
                self.selected = 0;
                self.selected_names.clear();
                if let Some(cfg) = &self.sub_config {
                    let mut c = cfg.lock().unwrap();
                    c.generation = c.generation.wrapping_add(1);
                }
            }

            KeyCode::Char('p') => {
                self.profile_picker_selected = self
                    .profiles
                    .iter()
                    .position(|p| p == &self.profile)
                    .unwrap_or(0);
                self.mode = Mode::ProfilePicker;
            }

            KeyCode::Char('r') => {
                self.palette_input = format!(
                    "--name {} -i {} {}",
                    random_name(),
                    self.tui_config.default_image,
                    self.tui_config.default_it_cmd,
                );
                self.mode = Mode::CommandPalette;
            }

            KeyCode::Char('R') => {
                self.palette_input = format!("--name {} -d ", random_name());
                self.mode = Mode::CommandPalette;
            }

            // Container actions — operate on multi-selection or highlighted row.
            KeyCode::Char('s') => self.begin_action(ConfirmAction::Stop),
            KeyCode::Char('S') => self.begin_action(ConfirmAction::Restart),
            KeyCode::Char('d') => self.begin_action(ConfirmAction::Remove),

            // Inspect overlay: show full detail for highlighted container.
            KeyCode::Enter | KeyCode::Char('i') => {
                if let Some(c) = self.containers.get(self.selected) {
                    self.pending_inspect = Some(c.name.clone());
                    self.inspect_scroll = 0;
                    self.mode = Mode::Inspect;
                }
            }

            // Images screen.
            KeyCode::Char('I') => {
                self.images_selected = 0;
                self.images_error = None;
                self.pending_image_ls = true;
                self.images_loading = true;
                self.mode = Mode::Images;
            }

            // Prune: target all exited containers regardless of selection.
            KeyCode::Char('P') => {
                let targets: Vec<String> = self
                    .containers
                    .iter()
                    .filter(|c| c.status != "running")
                    .map(|c| c.name.clone())
                    .collect();
                if targets.is_empty() {
                    self.status_message = Some("no exited containers to prune".to_string());
                } else {
                    self.confirm_action = Some(ConfirmAction::Remove);
                    self.confirm_targets = targets;
                    self.mode = Mode::Confirm;
                }
            }

            _ => {}
        }
    }

    fn on_key_profile_picker(&mut self, key: KeyEvent) {
        match key.code {
            KeyCode::Char('j') | KeyCode::Down => {
                if !self.profiles.is_empty() {
                    self.profile_picker_selected =
                        (self.profile_picker_selected + 1).min(self.profiles.len() - 1);
                }
            }
            KeyCode::Char('k') | KeyCode::Up => {
                self.profile_picker_selected = self.profile_picker_selected.saturating_sub(1);
            }
            KeyCode::Enter => {
                if let Some(chosen) = self.profiles.get(self.profile_picker_selected).cloned() {
                    if chosen != self.profile {
                        let old = std::mem::replace(&mut self.profile, chosen.clone());
                        log::debug!("profile switch: {} -> {}", old, chosen);
                        self.containers.clear();
                        self.selected = 0;
                        self.selected_names.clear();
                        self.tui_config = TuiConfig::load(&chosen);
                        // Update the target profile but do NOT bump generation yet.
                        // main.rs will stop the old VM first, then bump, so the
                        // new VM starts without a NAT relay port conflict.
                        if let Some(cfg) = &self.sub_config {
                            cfg.lock().unwrap().profile = chosen;
                        }
                        self.pending_profile_switch = Some(old);
                    }
                }
                self.mode = Mode::Normal;
            }
            KeyCode::Esc | KeyCode::Char('p') => {
                self.mode = Mode::Normal;
            }
            _ => {}
        }
    }

    fn on_key_palette(&mut self, key: KeyEvent) {
        match key.code {
            KeyCode::Esc => {
                self.palette_input.clear();
                self.mode = Mode::Normal;
            }
            KeyCode::Enter => {
                let input = self.palette_input.trim().to_string();
                if !input.is_empty() {
                    self.pending_run = Some(input);
                }
                self.palette_input.clear();
                self.mode = Mode::Normal;
            }
            KeyCode::Backspace => {
                self.palette_input.pop();
            }
            KeyCode::Char(c) => {
                self.palette_input.push(c);
            }
            _ => {}
        }
    }

    fn on_key_confirm(&mut self, key: KeyEvent) {
        match key.code {
            KeyCode::Char('y') | KeyCode::Char('Y') => {
                if let Some(action) = self.confirm_action.take() {
                    let targets = std::mem::take(&mut self.confirm_targets);
                    if action == ConfirmAction::ImageRm {
                        self.pending_image_rm = targets.into_iter().next();
                        self.mode = Mode::Images;
                    } else {
                        self.pending_action = Some((action, targets));
                        self.selected_names.clear();
                        self.mode = Mode::Normal;
                    }
                }
            }
            _ => {
                // Any key other than 'y' cancels — return to whichever screen initiated.
                let from_images = self.confirm_action == Some(ConfirmAction::ImageRm);
                self.confirm_action = None;
                self.confirm_targets.clear();
                self.mode = if from_images {
                    Mode::Images
                } else {
                    Mode::Normal
                };
            }
        }
    }

    fn on_key_confirm_quit(&mut self, key: KeyEvent) {
        match key.code {
            KeyCode::Char('y') | KeyCode::Char('Y') | KeyCode::Char('q') => {
                self.should_quit = true;
            }
            _ => {
                self.mode = Mode::Normal;
            }
        }
    }

    fn on_key_inspect(&mut self, key: KeyEvent) {
        match key.code {
            KeyCode::Esc | KeyCode::Char('q') => {
                self.mode = Mode::Normal;
                self.inspect_container = None;
            }
            KeyCode::Char('j') | KeyCode::Down => {
                self.inspect_scroll = self.inspect_scroll.saturating_add(1);
            }
            KeyCode::Char('k') | KeyCode::Up => {
                self.inspect_scroll = self.inspect_scroll.saturating_sub(1);
            }
            _ => {}
        }
    }

    fn on_key_images(&mut self, key: KeyEvent) {
        match key.code {
            KeyCode::Esc | KeyCode::Char('I') => {
                self.mode = Mode::Normal;
            }
            KeyCode::Char('j') | KeyCode::Down => {
                if !self.images.is_empty() {
                    self.images_selected = (self.images_selected + 1).min(self.images.len() - 1);
                }
            }
            KeyCode::Char('k') | KeyCode::Up => {
                self.images_selected = self.images_selected.saturating_sub(1);
            }
            KeyCode::Char('r') => {
                self.images_loading = true;
                self.images_error = None;
                self.pending_image_ls = true;
            }
            // Open the run command palette with the selected image pre-filled.
            KeyCode::Char('R') => {
                if let Some(img) = self.images.get(self.images_selected) {
                    self.palette_input = format!("--name {} -d {}", random_name(), img.reference,);
                    self.mode = Mode::CommandPalette;
                }
            }
            KeyCode::Char('p') => {
                self.image_pull_input.clear();
                self.mode = Mode::ImagePull;
            }
            KeyCode::Char('d') => {
                if let Some(img) = self.images.get(self.images_selected) {
                    self.confirm_action = Some(ConfirmAction::ImageRm);
                    self.confirm_targets = vec![img.reference.clone()];
                    self.mode = Mode::Confirm;
                }
            }
            KeyCode::Enter => {
                if let Some(img) = self.images.get(self.images_selected) {
                    self.pending_image_inspect = Some(img.reference.clone());
                    self.image_inspect_lines.clear();
                    self.image_inspect_loading = true;
                    self.image_inspect_scroll = 0;
                    self.mode = Mode::ImageInspect;
                }
            }
            _ => {}
        }
    }

    fn on_key_image_pull(&mut self, key: KeyEvent) {
        match key.code {
            KeyCode::Esc => {
                self.image_pull_input.clear();
                self.mode = Mode::Images;
            }
            KeyCode::Enter => {
                let input = self.image_pull_input.trim().to_string();
                if !input.is_empty() {
                    self.pending_image_pull = Some(input);
                }
                self.image_pull_input.clear();
                self.mode = Mode::Images;
            }
            KeyCode::Backspace => {
                self.image_pull_input.pop();
            }
            KeyCode::Char(c) => {
                self.image_pull_input.push(c);
            }
            _ => {}
        }
    }

    fn on_key_image_inspect(&mut self, key: KeyEvent) {
        match key.code {
            KeyCode::Esc | KeyCode::Char('q') => {
                self.image_inspect_lines.clear();
                self.mode = Mode::Images;
            }
            KeyCode::Char('j') | KeyCode::Down => {
                self.image_inspect_scroll = self.image_inspect_scroll.saturating_add(1);
            }
            KeyCode::Char('k') | KeyCode::Up => {
                self.image_inspect_scroll = self.image_inspect_scroll.saturating_sub(1);
            }
            _ => {}
        }
    }

    // -----------------------------------------------------------------------
    // Helpers
    // -----------------------------------------------------------------------

    /// Returns target names for an action: the multi-selection (in list order)
    /// if non-empty, otherwise the single highlighted container.
    fn action_targets(&self) -> Vec<String> {
        if !self.selected_names.is_empty() {
            self.containers
                .iter()
                .filter(|c| self.selected_names.contains(&c.name))
                .map(|c| c.name.clone())
                .collect()
        } else {
            self.containers
                .get(self.selected)
                .map(|c| vec![c.name.clone()])
                .unwrap_or_default()
        }
    }

    fn begin_action(&mut self, action: ConfirmAction) {
        let targets = self.action_targets();
        if targets.is_empty() {
            return;
        }
        // If the user asks to remove a container that is still running, upgrade
        // to StopAndRemove so they get a clear prompt and the stop happens first.
        let action = if action == ConfirmAction::Remove {
            let any_running = self
                .containers
                .iter()
                .filter(|c| targets.contains(&c.name))
                .any(|c| c.status == "running");
            if any_running {
                ConfirmAction::StopAndRemove
            } else {
                action
            }
        } else {
            action
        };
        self.confirm_action = Some(action);
        self.confirm_targets = targets;
        self.mode = Mode::Confirm;
    }

    #[allow(dead_code)]
    pub fn selected_container(&self) -> Option<&Container> {
        self.containers.get(self.selected)
    }

    /// Drain any pending inspect result delivered by the background thread.
    pub fn poll_inspect_result(&mut self) {
        if let Some(rx) = &self.inspect_result_rx {
            while let Ok(c) = rx.try_recv() {
                self.inspect_container = Some(c);
                // Clamp scroll in case the new result is shorter.
                self.inspect_scroll = 0;
            }
        }
    }

    /// Drain any image list result delivered by the background fetch thread.
    pub fn poll_image_ls_result(&mut self) {
        if let Some(rx) = &self.image_ls_rx {
            while let Ok(result) = rx.try_recv() {
                self.images_loading = false;
                match result {
                    Ok(list) => {
                        self.images = list;
                        self.images_error = None;
                        // Clamp selection to new list length.
                        if self.images_selected >= self.images.len() {
                            self.images_selected = self.images.len().saturating_sub(1);
                        }
                    }
                    Err(e) => {
                        self.images_error = Some(e);
                    }
                }
            }
        }
    }

    /// Drain any image inspect result delivered by the background fetch thread.
    pub fn poll_image_inspect_result(&mut self) {
        if let Some(rx) = &self.image_inspect_rx {
            while let Ok(result) = rx.try_recv() {
                self.image_inspect_loading = false;
                match result {
                    Ok(json) => {
                        self.image_inspect_lines = json.lines().map(|l| l.to_string()).collect();
                        self.image_inspect_scroll = 0;
                    }
                    Err(e) => {
                        self.image_inspect_lines = vec![format!("Error: {}", e)];
                    }
                }
            }
        }
    }

    pub fn refresh_age_secs(&self) -> u64 {
        self.last_refresh.elapsed().as_secs()
    }
}

fn clamp_selected(selected: &mut usize, len: usize) {
    if len == 0 {
        *selected = 0;
    } else if *selected >= len {
        *selected = len - 1;
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    fn parse(json: &str) -> SubscriptionMsg {
        serde_json::from_str(json).expect("parse failed")
    }

    #[test]
    fn test_parse_snapshot_empty() {
        let msg = parse(r#"{"type":"snapshot","containers":[],"vm_running":true}"#);
        match msg {
            SubscriptionMsg::Snapshot {
                containers,
                vm_running,
            } => {
                assert!(containers.is_empty());
                assert!(vm_running);
            }
            other => panic!("expected Snapshot, got {:?}", other),
        }
    }

    #[test]
    fn test_parse_snapshot_with_container() {
        let json = r#"{
            "type": "snapshot",
            "vm_running": true,
            "containers": [{
                "name": "web",
                "rootfs": "/rootfs/alpine",
                "status": "running",
                "pid": 99,
                "started_at": "2026-01-01T00:00:00Z"
            }]
        }"#;
        let msg = parse(json);
        match msg {
            SubscriptionMsg::Snapshot {
                containers,
                vm_running,
            } => {
                assert!(vm_running);
                assert_eq!(containers.len(), 1);
                let c = &containers[0];
                assert_eq!(c.name, "web");
                assert_eq!(c.status, "running");
                assert_eq!(c.pid, 99);
                assert_eq!(c.rootfs, "/rootfs/alpine");
                assert_eq!(c.started_at, "2026-01-01T00:00:00Z");
            }
            other => panic!("expected Snapshot, got {:?}", other),
        }
    }

    #[test]
    fn test_parse_container_started() {
        let json = r#"{
            "type": "container_started",
            "container": {
                "name": "worker",
                "rootfs": "/rootfs/alpine",
                "status": "running",
                "pid": 42,
                "started_at": "2026-01-01T00:00:00Z"
            }
        }"#;
        let msg = parse(json);
        match msg {
            SubscriptionMsg::ContainerStarted { container } => {
                assert_eq!(container.name, "worker");
            }
            other => panic!("expected ContainerStarted, got {:?}", other),
        }
    }

    #[test]
    fn test_parse_container_exited() {
        let json = r#"{"type":"container_exited","name":"foo","exit_code":0}"#;
        let msg = parse(json);
        match msg {
            SubscriptionMsg::ContainerExited { name, exit_code } => {
                assert_eq!(name, "foo");
                assert_eq!(exit_code, Some(0));
            }
            other => panic!("expected ContainerExited, got {:?}", other),
        }
    }

    #[test]
    fn test_parse_container_exited_no_exit_code() {
        let json = r#"{"type":"container_exited","name":"bar"}"#;
        let msg = parse(json);
        match msg {
            SubscriptionMsg::ContainerExited { name, exit_code } => {
                assert_eq!(name, "bar");
                assert_eq!(exit_code, None);
            }
            other => panic!("expected ContainerExited, got {:?}", other),
        }
    }

    #[test]
    fn test_parse_heartbeat() {
        let json = r#"{"type":"heartbeat","ts":12345}"#;
        let msg = parse(json);
        match msg {
            SubscriptionMsg::Heartbeat { ts } => {
                assert_eq!(ts, 12345);
            }
            other => panic!("expected Heartbeat, got {:?}", other),
        }
    }

    #[test]
    fn test_snapshot_vm_running_true() {
        let json = r#"{"type":"snapshot","containers":[],"vm_running":true}"#;
        let msg = parse(json);
        match msg {
            SubscriptionMsg::Snapshot { vm_running, .. } => assert!(vm_running),
            other => panic!("expected Snapshot, got {:?}", other),
        }
    }

    #[test]
    fn test_container_fields_default() {
        // Only required fields; optional ones should use defaults.
        let json = r#"{
            "type": "snapshot",
            "vm_running": false,
            "containers": [{
                "name": "minimal",
                "rootfs": "/rootfs",
                "status": "running",
                "pid": 1,
                "started_at": "2026-01-01T00:00:00Z"
            }]
        }"#;
        let msg = parse(json);
        match msg {
            SubscriptionMsg::Snapshot { containers, .. } => {
                let c = &containers[0];
                assert_eq!(c.exit_code, None);
                assert!(c.ports.is_empty());
                assert!(c.command.is_empty());
            }
            other => panic!("expected Snapshot, got {:?}", other),
        }
    }
}
